name: Approve pull request
on:
  pull_request:
    branches:
      - qa
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.10 64-bit
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
    - name: Lint with pylint
      run: |
        if (Test-Path -Path "tests") {
            pylint __init__.py
        }
    - name: Run pytest
      run: |
        if (Test-Path -Path "tests") {
            pytest tests/
        }
    - name: Check for required files and directories
      run: |
        if (Test-Path -Path "__init__.py") {
            echo "__init__.py found."
        } else {
            echo "__init__.py not found. Exiting."
            exit 1
        }
        if (Test-Path -Path "package.json") {
            echo "package.json found."
        } else {
            echo "package.json not found. Exiting."
            exit 1
        }
        if (Test-Path -Path "readme.md") {
            echo "readme.md found."
        } else {
            echo "readme.md not found. Exiting."
            exit 1
        }
        if (Test-Path -Path "docs") {
            echo "docs directory found."
        } else {
            echo "docs directory not found. Exiting."
            exit 1
        }
        if (Test-Path -Path "example") {
            echo "example directory found."
        } else {
            echo "example directory not found. Exiting."
            exit 1
        }
    - name: Approve Pull Request
      uses: juliangruber/merge-pull-request-action@v1.1.0
      with:
       github-token: ${{ secrets.TEST }}
       number: 10
